services:
  - type: web
    name: fb-messenger-command-bot
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      playwright install chromium
    startCommand: python main.py
    plan: free
